import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/sessionProvider";
import { getServerSession } from "next-auth";
import { createApolloClient } from "@/utils/appolloClient";
import { ApolloProvider } from "@apollo/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  const isClient = typeof window !== 'undefined';

  // Create Apollo Client only on the client side
  const apolloClient = isClient ? createApolloClient() : null;
  return (
    <html lang="en">
      <body className={inter.className}>

      <SessionProvider session={session}>
  {isClient && apolloClient ? (
    <ApolloProvider client={apolloClient}>
      {children}
    </ApolloProvider>
  ) : (
    children
  )}
</SessionProvider>

      </body>
    </html>
  );
}
